# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "cpus" {
  type    = string
  default = "1"
}

variable "disable_ipv6" {
  type    = string
  default = "true"
}

variable "disk_size" {
  type    = string
  default = "65536"
}

variable "headless" {
  type    = string
  default = "false"
}

variable "http_proxy" {
  type    = string
  default = "${env("http_proxy")}"
}

variable "https_proxy" {
  type    = string
  default = "${env("https_proxy")}"
}

variable "iso_checksum" {
  type    = string
  default = "https://old-releases.ubuntu.com/releases/20.04.2/SHA256SUMS"
}

variable "iso_checksum_type" {
  type    = string
  default = "file"
}

variable "iso_name" {
  type    = string
  default = "ubuntu-20.04.2-live-server-amd64.iso"
}

variable "iso_url" {
  type    = string
  default = "https://old-releases.ubuntu.com/releases/20.04.2/ubuntu-20.04.2-live-server-amd64.iso"
}

variable "memory" {
  type    = string
  default = "1024"
}

variable "no_proxy" {
  type    = string
  default = "${env("no_proxy")}"
}

variable "ssh_password" {
  type    = string
  default = "vagrant"
}

variable "ssh_username" {
  type    = string
  default = "vagrant"
}

variable "update" {
  type    = string
  default = "true"
}

variable "vagrantfile_template" {
  type    = string
  default = ""
}

variable "version" {
  type    = string
  default = "0.1"
}

variable "virtualbox_guest_os_type" {
  type    = string
  default = "Ubuntu_64"
}

variable "vm_name" {
  type    = string
  default = "packer-ubuntu-20.04-amd64"
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "virtualbox-iso" "autogenerated_1" {
  boot_command            = ["<enter><enter><f6><esc><wait5>", "<wait>autoinstall <wait>ds=nocloud-net;", "<wait>s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/", "<enter>"]
  boot_wait               = "5s"
  disk_size               = "${var.disk_size}"
  guest_additions_path    = "VBoxGuestAdditions_{{ .Version }}.iso"
  guest_os_type           = "${var.virtualbox_guest_os_type}"
  hard_drive_interface    = "sata"
  headless                = "${var.headless}"
  http_directory          = "http"
  iso_checksum            = "${var.iso_checksum_type}:${var.iso_checksum}"
  iso_urls                = ["iso/${var.iso_name}", "${var.iso_url}"]
  output_directory        = "output-${var.vm_name}-virtualbox-iso"
  shutdown_command        = "echo '${var.ssh_password}'|sudo -S shutdown -P now"
  ssh_handshake_attempts  = "20"
  ssh_password            = "${var.ssh_password}"
  ssh_pty                 = true
  ssh_timeout             = "1h"
  ssh_username            = "${var.ssh_username}"
  vboxmanage              = [["modifyvm", "{{ .Name }}", "--usb", "on"], ["modifyvm", "{{ .Name }}", "--usbehci", "on"], ["modifyvm", "{{ .Name }}", "--audio", "none"], ["modifyvm", "{{ .Name }}", "--vram", "16"], ["modifyvm", "{{ .Name }}", "--vrde", "off"], ["modifyvm", "{{ .Name }}", "--nictype1", "virtio"], ["modifyvm", "{{ .Name }}", "--memory", "${var.memory}"], ["modifyvm", "{{ .Name }}", "--cpus", "${var.cpus}"]]
  virtualbox_version_file = ".vbox_version"
  vm_name                 = "${var.vm_name}"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "shell" {
    environment_vars  = ["DEBIAN_FRONTEND=noninteractive", "UPDATE=${var.update}", "DISABLE_IPV6=${var.disable_ipv6}", "SSH_USERNAME=${var.ssh_username}", "SSH_PASSWORD=${var.ssh_password}", "http_proxy=${var.http_proxy}", "https_proxy=${var.https_proxy}", "no_proxy=${var.no_proxy}"]
    execute_command   = "echo '${var.ssh_password}'|{{ .Vars }} sudo -E -S bash '{{ .Path }}'"
    expect_disconnect = true
    scripts           = ["scripts/update.sh", "scripts/vagrant.sh", "scripts/virtualbox.sh", "scripts/minimize.sh", "scripts/firmware_setup.sh", "scripts/cleanup.sh"]
  }

  post-processor "vagrant" {
    compression_level = "9"
    output            = "backpack.box"
  }
}
