name: build_and_release

on:
  # Run on all pull requests and all pushes to master
  push:
    branches: [ master ]
  pull_request:

  # Allow running this workflow manually
  workflow_dispatch:

env:
  DEFINES: "DISPLAY=0:.0"

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build box
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          target: backpack.json

      - name: Release box
        id: release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./backpack.box
          asset_name: backpack.box
          asset_content_type: application/octet-stream
